# Generated by Django 4.2.11 on 2024-03-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bill_month', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=3, max_digits=9)),
                ('image', models.ImageField(upload_to='media/')),
                ('house_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], max_length=20)),
                ('category', models.CharField(choices=[('SINGLE', 'single'), ('DOUBLE', 'double_room'), ('DOUBLE SELF', 'double_self'), ('ONE BEDROOM', 'one bedroom'), ('TWO BEDROOM', 'two bedroom')], max_length=20)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricBill',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.bill')),
            ],
            bases=('property.bill',),
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.bill')),
            ],
            bases=('property.bill',),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('no_houses', models.IntegerField()),
                ('houses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.house')),
                ('owner', models.ManyToManyField(related_name='properties', to='accounts.owner')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='electric_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.electricbill'),
        ),
        migrations.AddField(
            model_name='house',
            name='water_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.waterbill'),
        ),
    ]
