# Generated by Django 4.2.11 on 2024-03-23 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='houses',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ManyToManyField(related_name='houses', to='accounts.owner'),
        ),
        migrations.AddField(
            model_name='house',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='property.property'),
            preserve_default=False,
        ),
    ]
