# Generated by Django 4.2.11 on 2024-03-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('property', '0002_remove_property_houses_remove_property_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='electric_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.electricbill'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='tenant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='house',
            name='water_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.waterbill'),
        ),
    ]
