# Generated by Django 4.2.11 on 2024-03-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_house_electric_bill_alter_house_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='no_houses',
        ),
    ]
