# Generated by Django 4.2.11 on 2024-03-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], max_length=20, null=True),
        ),
    ]
