# Generated by Django 4.2.11 on 2024-03-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='property',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='property.property'),
        ),
    ]
