# Generated by Django 4.2.11 on 2024-03-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_house_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['house_number']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
